[package]
name = "positron"
version = "0.1.0"
authors = ["antoine <antoine.sb@orange.fr>"]
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]